/*
 * Copyright (c) 2026, ScapePath
 * All rights reserved. BSD 2-Clause. See LICENSE file.
 */
package com.scapepath.plugin.game;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import lombok.Value;
import net.runelite.api.gameval.VarbitID;

/**
 * The auditable mapping of Combat Achievement state to the stable RuneLite {@code VarbitID}
 * constants that store it.
 *
 * <p>Unlike the Collection Log (whose per-item state is interface-gated and only partially
 * named), RuneLite's {@code gameval} exposes a stable, named per-task completion varbit for
 * <b>every</b> Combat Achievement task ({@code CA_TASK_&lt;ACTIVITY&gt;_&lt;TYPE&gt;_&lt;N&gt;_COMPLETED}).
 * These are account-stored varbits delivered with the login varp block, so they are reliable
 * whenever logged in and require no interface to be opened and no polling.</p>
 *
 * <p>The plugin sends only player <b>state</b>: which tasks are complete (by stable id), the
 * per-tier completed-task counts, tier status, points, and each tier's points threshold. The
 * website owns all static knowledge &mdash; which task belongs to which tier, its boss/activity,
 * its point value, and the full universe of tasks needed to compute "missing". The task id is
 * the RuneLite {@code VarbitID} constant name itself; it is stable across game updates and
 * independent of wiki wording, and the website must key on it, never on a display string.</p>
 *
 * <p>Reflection-free by design: every varbit is referenced by its named constant, so the
 * mapping is compile-checked and breaks loudly (not silently) if RuneLite renames a constant
 * on a version bump. Generated from RuneLite {@code runelite-api} 1.12.38.</p>
 */
public final class CombatAchievementDefinitions
{
	/** One Combat Achievement task and the varbit holding its completion. */
	@Value
	public static class TaskDef
	{
		/** Stable task id: the RuneLite {@code VarbitID} constant name. */
		String id;
		int varbitId;
	}

	/** One Combat Achievement tier and the varbits describing its aggregate state. */
	@Value
	public static class TierDef
	{
		/** Stable tier id, e.g. {@code "EASY"}. */
		String tier;
		/** Raw tier status varbit (game-defined; interpreted by the website). */
		int statusVarbitId;
		/** Count of completed tasks in this tier. */
		int completedCountVarbitId;
		/** Points threshold required to complete this tier. */
		int thresholdVarbitId;
	}

	/** A task varbit value of at least this is treated as completed. */
	public static final int TASK_COMPLETE_MIN = 1;

	/** VarPlayer/varbit holding the account's total Combat Achievement points. */
	public static final int POINTS_VARBIT = VarbitID.CA_POINTS;

	private static final List<TaskDef> TASKS = buildTasks();
	private static final List<TierDef> TIERS = buildTiers();
	private static final Set<Integer> VARBIT_IDS = collectVarbitIds();

	private CombatAchievementDefinitions()
	{
	}

	/** Every enumerated Combat Achievement task, in a fixed order. */
	public static List<TaskDef> tasks()
	{
		return TASKS;
	}

	/** The six Combat Achievement tiers, easiest first. */
	public static List<TierDef> tiers()
	{
		return TIERS;
	}

	/** Every varbit id this section reads &mdash; used to trigger targeted snapshot rebuilds. */
	public static Set<Integer> varbitIds()
	{
		return VARBIT_IDS;
	}

	private static void t(List<TaskDef> l, String id, int varbitId)
	{
		l.add(new TaskDef(id, varbitId));
	}

	private static List<TaskDef> buildTasks()
	{
		final List<TaskDef> l = new ArrayList<>(398);
		t(l, "CA_TASK_ABBERANT_SPECTRE_KILLCOUNT_1_COMPLETED", VarbitID.CA_TASK_ABBERANT_SPECTRE_KILLCOUNT_1_COMPLETED);
		t(l, "CA_TASK_ABYSSALSIRE_KILLCOUNT_1_COMPLETED", VarbitID.CA_TASK_ABYSSALSIRE_KILLCOUNT_1_COMPLETED);
		t(l, "CA_TASK_ABYSSALSIRE_KILLCOUNT_2_COMPLETED", VarbitID.CA_TASK_ABYSSALSIRE_KILLCOUNT_2_COMPLETED);
		t(l, "CA_TASK_ABYSSALSIRE_MECHANICAL_1_COMPLETED", VarbitID.CA_TASK_ABYSSALSIRE_MECHANICAL_1_COMPLETED);
		t(l, "CA_TASK_ABYSSALSIRE_MECHANICAL_2_COMPLETED", VarbitID.CA_TASK_ABYSSALSIRE_MECHANICAL_2_COMPLETED);
		t(l, "CA_TASK_ABYSSALSIRE_MECHANICAL_3_COMPLETED", VarbitID.CA_TASK_ABYSSALSIRE_MECHANICAL_3_COMPLETED);
		t(l, "CA_TASK_ABYSSALSIRE_MECHANICAL_4_COMPLETED", VarbitID.CA_TASK_ABYSSALSIRE_MECHANICAL_4_COMPLETED);
		t(l, "CA_TASK_ABYSSALSIRE_PERFECTION_1_COMPLETED", VarbitID.CA_TASK_ABYSSALSIRE_PERFECTION_1_COMPLETED);
		t(l, "CA_TASK_ABYSSALSIRE_PERFECTION_2_COMPLETED", VarbitID.CA_TASK_ABYSSALSIRE_PERFECTION_2_COMPLETED);
		t(l, "CA_TASK_ARMADYL_KILLCOUNT_1_COMPLETED", VarbitID.CA_TASK_ARMADYL_KILLCOUNT_1_COMPLETED);
		t(l, "CA_TASK_ARMADYL_KILLCOUNT_2_COMPLETED", VarbitID.CA_TASK_ARMADYL_KILLCOUNT_2_COMPLETED);
		t(l, "CA_TASK_ARMADYL_MECHANICAL_1_COMPLETED", VarbitID.CA_TASK_ARMADYL_MECHANICAL_1_COMPLETED);
		t(l, "CA_TASK_ARMADYL_MECHANICAL_2_COMPLETED", VarbitID.CA_TASK_ARMADYL_MECHANICAL_2_COMPLETED);
		t(l, "CA_TASK_ARMADYL_PERFECTION_1_COMPLETED", VarbitID.CA_TASK_ARMADYL_PERFECTION_1_COMPLETED);
		t(l, "CA_TASK_ARMADYL_RESTRICTION_1_COMPLETED", VarbitID.CA_TASK_ARMADYL_RESTRICTION_1_COMPLETED);
		t(l, "CA_TASK_ARMADYL_STAMINA_1_COMPLETED", VarbitID.CA_TASK_ARMADYL_STAMINA_1_COMPLETED);
		t(l, "CA_TASK_BANDOS_KILLCOUNT_1_COMPLETED", VarbitID.CA_TASK_BANDOS_KILLCOUNT_1_COMPLETED);
		t(l, "CA_TASK_BANDOS_KILLCOUNT_2_COMPLETED", VarbitID.CA_TASK_BANDOS_KILLCOUNT_2_COMPLETED);
		t(l, "CA_TASK_BANDOS_MECHANICAL_1_COMPLETED", VarbitID.CA_TASK_BANDOS_MECHANICAL_1_COMPLETED);
		t(l, "CA_TASK_BANDOS_MECHANICAL_2_COMPLETED", VarbitID.CA_TASK_BANDOS_MECHANICAL_2_COMPLETED);
		t(l, "CA_TASK_BANDOS_MECHANICAL_3_COMPLETED", VarbitID.CA_TASK_BANDOS_MECHANICAL_3_COMPLETED);
		t(l, "CA_TASK_BANDOS_PERFECTION_1_COMPLETED", VarbitID.CA_TASK_BANDOS_PERFECTION_1_COMPLETED);
		t(l, "CA_TASK_BANDOS_PERFECTION_2_COMPLETED", VarbitID.CA_TASK_BANDOS_PERFECTION_2_COMPLETED);
		t(l, "CA_TASK_BANDOS_STAMINA_1_COMPLETED", VarbitID.CA_TASK_BANDOS_STAMINA_1_COMPLETED);
		t(l, "CA_TASK_BARROWS_KILLCOUNT_1_COMPLETED", VarbitID.CA_TASK_BARROWS_KILLCOUNT_1_COMPLETED);
		t(l, "CA_TASK_BARROWS_KILLCOUNT_2_COMPLETED", VarbitID.CA_TASK_BARROWS_KILLCOUNT_2_COMPLETED);
		t(l, "CA_TASK_BARROWS_MECHANICAL_1_COMPLETED", VarbitID.CA_TASK_BARROWS_MECHANICAL_1_COMPLETED);
		t(l, "CA_TASK_BARROWS_PERFECTION_1_COMPLETED", VarbitID.CA_TASK_BARROWS_PERFECTION_1_COMPLETED);
		t(l, "CA_TASK_BARROWS_RESTRICTION_1_COMPLETED", VarbitID.CA_TASK_BARROWS_RESTRICTION_1_COMPLETED);
		t(l, "CA_TASK_BARROWS_RESTRICTION_2_COMPLETED", VarbitID.CA_TASK_BARROWS_RESTRICTION_2_COMPLETED);
		t(l, "CA_TASK_BARROWS_RESTRICTION_3_COMPLETED", VarbitID.CA_TASK_BARROWS_RESTRICTION_3_COMPLETED);
		t(l, "CA_TASK_BASILISK_KNIGHT_KILLCOUNT_1_COMPLETED", VarbitID.CA_TASK_BASILISK_KNIGHT_KILLCOUNT_1_COMPLETED);
		t(l, "CA_TASK_BLACK_DRAGON_KILLCOUNT_1_COMPLETED", VarbitID.CA_TASK_BLACK_DRAGON_KILLCOUNT_1_COMPLETED);
		t(l, "CA_TASK_BLOODVELD_KILLCOUNT_1_COMPLETED", VarbitID.CA_TASK_BLOODVELD_KILLCOUNT_1_COMPLETED);
		t(l, "CA_TASK_BRUTAL_BLACK_DRAGON_KILLCOUNT_1_COMPLETED", VarbitID.CA_TASK_BRUTAL_BLACK_DRAGON_KILLCOUNT_1_COMPLETED);
		t(l, "CA_TASK_BRYOPHYTA_KILLCOUNT_1_COMPLETED", VarbitID.CA_TASK_BRYOPHYTA_KILLCOUNT_1_COMPLETED);
		t(l, "CA_TASK_BRYOPHYTA_KILLCOUNT_2_COMPLETED", VarbitID.CA_TASK_BRYOPHYTA_KILLCOUNT_2_COMPLETED);
		t(l, "CA_TASK_BRYOPHYTA_MECHANICAL_1_COMPLETED", VarbitID.CA_TASK_BRYOPHYTA_MECHANICAL_1_COMPLETED);
		t(l, "CA_TASK_BRYOPHYTA_MECHANICAL_2_COMPLETED", VarbitID.CA_TASK_BRYOPHYTA_MECHANICAL_2_COMPLETED);
		t(l, "CA_TASK_BRYOPHYTA_PERFECTION_1_COMPLETED", VarbitID.CA_TASK_BRYOPHYTA_PERFECTION_1_COMPLETED);
		t(l, "CA_TASK_BRYOPHYTA_RESTRICTION_1_COMPLETED", VarbitID.CA_TASK_BRYOPHYTA_RESTRICTION_1_COMPLETED);
		t(l, "CA_TASK_BRYOPHYTA_RESTRICTION_2_COMPLETED", VarbitID.CA_TASK_BRYOPHYTA_RESTRICTION_2_COMPLETED);
		t(l, "CA_TASK_CALLISTO_KILLCOUNT_1_COMPLETED", VarbitID.CA_TASK_CALLISTO_KILLCOUNT_1_COMPLETED);
		t(l, "CA_TASK_CALLISTO_KILLCOUNT_2_COMPLETED", VarbitID.CA_TASK_CALLISTO_KILLCOUNT_2_COMPLETED);
		t(l, "CA_TASK_CATA_BOSS_KILLCOUNT_1_COMPLETED", VarbitID.CA_TASK_CATA_BOSS_KILLCOUNT_1_COMPLETED);
		t(l, "CA_TASK_CATA_BOSS_KILLCOUNT_2_COMPLETED", VarbitID.CA_TASK_CATA_BOSS_KILLCOUNT_2_COMPLETED);
		t(l, "CA_TASK_CATA_BOSS_MECHANICAL_1_COMPLETED", VarbitID.CA_TASK_CATA_BOSS_MECHANICAL_1_COMPLETED);
		t(l, "CA_TASK_CATA_BOSS_PERFECTION_1_COMPLETED", VarbitID.CA_TASK_CATA_BOSS_PERFECTION_1_COMPLETED);
		t(l, "CA_TASK_CATA_BOSS_RESTRICTION_1_COMPLETED", VarbitID.CA_TASK_CATA_BOSS_RESTRICTION_1_COMPLETED);
		t(l, "CA_TASK_CATA_BOSS_RESTRICTION_2_COMPLETED", VarbitID.CA_TASK_CATA_BOSS_RESTRICTION_2_COMPLETED);
		t(l, "CA_TASK_CATA_BOSS_RESTRICTION_3_COMPLETED", VarbitID.CA_TASK_CATA_BOSS_RESTRICTION_3_COMPLETED);
		t(l, "CA_TASK_CERBERUS_KILLCOUNT_1_COMPLETED", VarbitID.CA_TASK_CERBERUS_KILLCOUNT_1_COMPLETED);
		t(l, "CA_TASK_CERBERUS_KILLCOUNT_2_COMPLETED", VarbitID.CA_TASK_CERBERUS_KILLCOUNT_2_COMPLETED);
		t(l, "CA_TASK_CERBERUS_MECHANICAL_1_COMPLETED", VarbitID.CA_TASK_CERBERUS_MECHANICAL_1_COMPLETED);
		t(l, "CA_TASK_CERBERUS_MECHANICAL_2_COMPLETED", VarbitID.CA_TASK_CERBERUS_MECHANICAL_2_COMPLETED);
		t(l, "CA_TASK_CERBERUS_PERFECTION_1_COMPLETED", VarbitID.CA_TASK_CERBERUS_PERFECTION_1_COMPLETED);
		t(l, "CA_TASK_CERBERUS_PERFECTION_2_COMPLETED", VarbitID.CA_TASK_CERBERUS_PERFECTION_2_COMPLETED);
		t(l, "CA_TASK_CHAOSELE_KILLCOUNT_1_COMPLETED", VarbitID.CA_TASK_CHAOSELE_KILLCOUNT_1_COMPLETED);
		t(l, "CA_TASK_CHAOSELE_KILLCOUNT_2_COMPLETED", VarbitID.CA_TASK_CHAOSELE_KILLCOUNT_2_COMPLETED);
		t(l, "CA_TASK_CHAOSELE_MECHANICAL_1_COMPLETED", VarbitID.CA_TASK_CHAOSELE_MECHANICAL_1_COMPLETED);
		t(l, "CA_TASK_CHAOSELE_PERFECTION_1_COMPLETED", VarbitID.CA_TASK_CHAOSELE_PERFECTION_1_COMPLETED);
		t(l, "CA_TASK_CHAOSFANATIC_KILLCOUNT_1_COMPLETED", VarbitID.CA_TASK_CHAOSFANATIC_KILLCOUNT_1_COMPLETED);
		t(l, "CA_TASK_CHAOSFANATIC_KILLCOUNT_2_COMPLETED", VarbitID.CA_TASK_CHAOSFANATIC_KILLCOUNT_2_COMPLETED);
		t(l, "CA_TASK_CHAOSFANATIC_PERFECTION_1_COMPLETED", VarbitID.CA_TASK_CHAOSFANATIC_PERFECTION_1_COMPLETED);
		t(l, "CA_TASK_CHAOSFANATIC_RESTRICTION_1_COMPLETED", VarbitID.CA_TASK_CHAOSFANATIC_RESTRICTION_1_COMPLETED);
		t(l, "CA_TASK_CORP_KILLCOUNT_1_COMPLETED", VarbitID.CA_TASK_CORP_KILLCOUNT_1_COMPLETED);
		t(l, "CA_TASK_CORP_KILLCOUNT_2_COMPLETED", VarbitID.CA_TASK_CORP_KILLCOUNT_2_COMPLETED);
		t(l, "CA_TASK_CORP_PERFECTION_1_COMPLETED", VarbitID.CA_TASK_CORP_PERFECTION_1_COMPLETED);
		t(l, "CA_TASK_CORP_RESTRICTION_1_COMPLETED", VarbitID.CA_TASK_CORP_RESTRICTION_1_COMPLETED);
		t(l, "CA_TASK_CORP_RESTRICTION_2_COMPLETED", VarbitID.CA_TASK_CORP_RESTRICTION_2_COMPLETED);
		t(l, "CA_TASK_CRAZYARCHAEOLOGIST_KILLCOUNT_1_COMPLETED", VarbitID.CA_TASK_CRAZYARCHAEOLOGIST_KILLCOUNT_1_COMPLETED);
		t(l, "CA_TASK_CRAZYARCHAEOLOGIST_KILLCOUNT_2_COMPLETED", VarbitID.CA_TASK_CRAZYARCHAEOLOGIST_KILLCOUNT_2_COMPLETED);
		t(l, "CA_TASK_CRAZYARCHAEOLOGIST_MECHANICAL_1_COMPLETED", VarbitID.CA_TASK_CRAZYARCHAEOLOGIST_MECHANICAL_1_COMPLETED);
		t(l, "CA_TASK_CRAZYARCHAEOLOGIST_PERFECTION_1_COMPLETED", VarbitID.CA_TASK_CRAZYARCHAEOLOGIST_PERFECTION_1_COMPLETED);
		t(l, "CA_TASK_DEMONIC_GORILLA_KILLCOUNT_1_COMPLETED", VarbitID.CA_TASK_DEMONIC_GORILLA_KILLCOUNT_1_COMPLETED);
		t(l, "CA_TASK_DEMONIC_GORILLA_RESTRICTION_1_COMPLETED", VarbitID.CA_TASK_DEMONIC_GORILLA_RESTRICTION_1_COMPLETED);
		t(l, "CA_TASK_DERANGEDARCHAEOLOGIST_KILLCOUNT_1_COMPLETED", VarbitID.CA_TASK_DERANGEDARCHAEOLOGIST_KILLCOUNT_1_COMPLETED);
		t(l, "CA_TASK_DERANGEDARCHAEOLOGIST_KILLCOUNT_2_COMPLETED", VarbitID.CA_TASK_DERANGEDARCHAEOLOGIST_KILLCOUNT_2_COMPLETED);
		t(l, "CA_TASK_DERANGEDARCHAEOLOGIST_MECHANICAL_1_COMPLETED", VarbitID.CA_TASK_DERANGEDARCHAEOLOGIST_MECHANICAL_1_COMPLETED);
		t(l, "CA_TASK_DERANGEDARCHAEOLOGIST_PERFECTION_1_COMPLETED", VarbitID.CA_TASK_DERANGEDARCHAEOLOGIST_PERFECTION_1_COMPLETED);
		t(l, "CA_TASK_FIRE_GIANT_KILLCOUNT_1_COMPLETED", VarbitID.CA_TASK_FIRE_GIANT_KILLCOUNT_1_COMPLETED);
		t(l, "CA_TASK_GALVEK_SPEED_1_COMPLETED", VarbitID.CA_TASK_GALVEK_SPEED_1_COMPLETED);
		t(l, "CA_TASK_GARGBOSS_KILLCOUNT_1_COMPLETED", VarbitID.CA_TASK_GARGBOSS_KILLCOUNT_1_COMPLETED);
		t(l, "CA_TASK_GARGBOSS_KILLCOUNT_2_COMPLETED", VarbitID.CA_TASK_GARGBOSS_KILLCOUNT_2_COMPLETED);
		t(l, "CA_TASK_GARGBOSS_MECHANICAL_1_COMPLETED", VarbitID.CA_TASK_GARGBOSS_MECHANICAL_1_COMPLETED);
		t(l, "CA_TASK_GARGBOSS_MECHANICAL_2_COMPLETED", VarbitID.CA_TASK_GARGBOSS_MECHANICAL_2_COMPLETED);
		t(l, "CA_TASK_GARGBOSS_MECHANICAL_3_COMPLETED", VarbitID.CA_TASK_GARGBOSS_MECHANICAL_3_COMPLETED);
		t(l, "CA_TASK_GARGBOSS_MECHANICAL_4_COMPLETED", VarbitID.CA_TASK_GARGBOSS_MECHANICAL_4_COMPLETED);
		t(l, "CA_TASK_GARGBOSS_MECHANICAL_5_COMPLETED", VarbitID.CA_TASK_GARGBOSS_MECHANICAL_5_COMPLETED);
		t(l, "CA_TASK_GARGBOSS_MECHANICAL_6_COMPLETED", VarbitID.CA_TASK_GARGBOSS_MECHANICAL_6_COMPLETED);
		t(l, "CA_TASK_GARGBOSS_PERFECTION_1_COMPLETED", VarbitID.CA_TASK_GARGBOSS_PERFECTION_1_COMPLETED);
		t(l, "CA_TASK_GARGBOSS_PERFECTION_2_COMPLETED", VarbitID.CA_TASK_GARGBOSS_PERFECTION_2_COMPLETED);
		t(l, "CA_TASK_GARGBOSS_SPEED_1_COMPLETED", VarbitID.CA_TASK_GARGBOSS_SPEED_1_COMPLETED);
		t(l, "CA_TASK_GARGBOSS_SPEED_2_COMPLETED", VarbitID.CA_TASK_GARGBOSS_SPEED_2_COMPLETED);
		t(l, "CA_TASK_GARGBOSS_SPEED_3_COMPLETED", VarbitID.CA_TASK_GARGBOSS_SPEED_3_COMPLETED);
		t(l, "CA_TASK_GARGBOSS_STAMINA_1_COMPLETED", VarbitID.CA_TASK_GARGBOSS_STAMINA_1_COMPLETED);
		t(l, "CA_TASK_GARGBOSS_STAMINA_2_COMPLETED", VarbitID.CA_TASK_GARGBOSS_STAMINA_2_COMPLETED);
		t(l, "CA_TASK_GARGOYLE_KILLCOUNT_1_COMPLETED", VarbitID.CA_TASK_GARGOYLE_KILLCOUNT_1_COMPLETED);
		t(l, "CA_TASK_GAUNTLET_HM_KILLCOUNT_1_COMPLETED", VarbitID.CA_TASK_GAUNTLET_HM_KILLCOUNT_1_COMPLETED);
		t(l, "CA_TASK_GAUNTLET_HM_KILLCOUNT_2_COMPLETED", VarbitID.CA_TASK_GAUNTLET_HM_KILLCOUNT_2_COMPLETED);
		t(l, "CA_TASK_GAUNTLET_HM_KILLCOUNT_3_COMPLETED", VarbitID.CA_TASK_GAUNTLET_HM_KILLCOUNT_3_COMPLETED);
		t(l, "CA_TASK_GAUNTLET_HM_PERFECTION_1_COMPLETED", VarbitID.CA_TASK_GAUNTLET_HM_PERFECTION_1_COMPLETED);
		t(l, "CA_TASK_GAUNTLET_HM_PERFECTION_2_COMPLETED", VarbitID.CA_TASK_GAUNTLET_HM_PERFECTION_2_COMPLETED);
		t(l, "CA_TASK_GAUNTLET_HM_RESTRICTION_1_COMPLETED", VarbitID.CA_TASK_GAUNTLET_HM_RESTRICTION_1_COMPLETED);
		t(l, "CA_TASK_GAUNTLET_HM_RESTRICTION_2_COMPLETED", VarbitID.CA_TASK_GAUNTLET_HM_RESTRICTION_2_COMPLETED);
		t(l, "CA_TASK_GAUNTLET_HM_RESTRICTION_3_COMPLETED", VarbitID.CA_TASK_GAUNTLET_HM_RESTRICTION_3_COMPLETED);
		t(l, "CA_TASK_GAUNTLET_HM_RESTRICTION_4_COMPLETED", VarbitID.CA_TASK_GAUNTLET_HM_RESTRICTION_4_COMPLETED);
		t(l, "CA_TASK_GAUNTLET_HM_SPEED_1_COMPLETED", VarbitID.CA_TASK_GAUNTLET_HM_SPEED_1_COMPLETED);
		t(l, "CA_TASK_GAUNTLET_HM_SPEED_2_COMPLETED", VarbitID.CA_TASK_GAUNTLET_HM_SPEED_2_COMPLETED);
		t(l, "CA_TASK_GAUNTLET_KILLCOUNT_1_COMPLETED", VarbitID.CA_TASK_GAUNTLET_KILLCOUNT_1_COMPLETED);
		t(l, "CA_TASK_GAUNTLET_KILLCOUNT_2_COMPLETED", VarbitID.CA_TASK_GAUNTLET_KILLCOUNT_2_COMPLETED);
		t(l, "CA_TASK_GAUNTLET_PERFECTION_1_COMPLETED", VarbitID.CA_TASK_GAUNTLET_PERFECTION_1_COMPLETED);
		t(l, "CA_TASK_GAUNTLET_PERFECTION_2_COMPLETED", VarbitID.CA_TASK_GAUNTLET_PERFECTION_2_COMPLETED);
		t(l, "CA_TASK_GAUNTLET_RESTRICTION_1_COMPLETED", VarbitID.CA_TASK_GAUNTLET_RESTRICTION_1_COMPLETED);
		t(l, "CA_TASK_GAUNTLET_RESTRICTION_2_COMPLETED", VarbitID.CA_TASK_GAUNTLET_RESTRICTION_2_COMPLETED);
		t(l, "CA_TASK_GAUNTLET_RESTRICTION_3_COMPLETED", VarbitID.CA_TASK_GAUNTLET_RESTRICTION_3_COMPLETED);
		t(l, "CA_TASK_GAUNTLET_RESTRICTION_4_COMPLETED", VarbitID.CA_TASK_GAUNTLET_RESTRICTION_4_COMPLETED);
		t(l, "CA_TASK_GAUNTLET_SPEED_1_COMPLETED", VarbitID.CA_TASK_GAUNTLET_SPEED_1_COMPLETED);
		t(l, "CA_TASK_GAUNTLET_SPEED_2_COMPLETED", VarbitID.CA_TASK_GAUNTLET_SPEED_2_COMPLETED);
		t(l, "CA_TASK_GLOUGH_SPEED_1_COMPLETED", VarbitID.CA_TASK_GLOUGH_SPEED_1_COMPLETED);
		t(l, "CA_TASK_GREATER_DEMON_KILLCOUNT_1_COMPLETED", VarbitID.CA_TASK_GREATER_DEMON_KILLCOUNT_1_COMPLETED);
		t(l, "CA_TASK_GREATER_DEMON_RESTRICTION_1_COMPLETED", VarbitID.CA_TASK_GREATER_DEMON_RESTRICTION_1_COMPLETED);
		t(l, "CA_TASK_HELLHOUND_KILLCOUNT_1_COMPLETED", VarbitID.CA_TASK_HELLHOUND_KILLCOUNT_1_COMPLETED);
		t(l, "CA_TASK_HESPORI_KILLCOUNT_1_COMPLETED", VarbitID.CA_TASK_HESPORI_KILLCOUNT_1_COMPLETED);
		t(l, "CA_TASK_HESPORI_MECHANICAL_1_COMPLETED", VarbitID.CA_TASK_HESPORI_MECHANICAL_1_COMPLETED);
		t(l, "CA_TASK_HESPORI_MECHANICAL_2_COMPLETED", VarbitID.CA_TASK_HESPORI_MECHANICAL_2_COMPLETED);
		t(l, "CA_TASK_HESPORI_RESTRICTION_1_COMPLETED", VarbitID.CA_TASK_HESPORI_RESTRICTION_1_COMPLETED);
		t(l, "CA_TASK_HESPORI_SPEED_1_COMPLETED", VarbitID.CA_TASK_HESPORI_SPEED_1_COMPLETED);
		t(l, "CA_TASK_HESPORI_SPEED_2_COMPLETED", VarbitID.CA_TASK_HESPORI_SPEED_2_COMPLETED);
		t(l, "CA_TASK_HILLGIANT_BOSS_KILLCOUNT_1_COMPLETED", VarbitID.CA_TASK_HILLGIANT_BOSS_KILLCOUNT_1_COMPLETED);
		t(l, "CA_TASK_HILLGIANT_BOSS_KILLCOUNT_2_COMPLETED", VarbitID.CA_TASK_HILLGIANT_BOSS_KILLCOUNT_2_COMPLETED);
		t(l, "CA_TASK_HILLGIANT_BOSS_MECHANICAL_1_COMPLETED", VarbitID.CA_TASK_HILLGIANT_BOSS_MECHANICAL_1_COMPLETED);
		t(l, "CA_TASK_HILLGIANT_BOSS_MECHANICAL_2_COMPLETED", VarbitID.CA_TASK_HILLGIANT_BOSS_MECHANICAL_2_COMPLETED);
		t(l, "CA_TASK_HILLGIANT_BOSS_PERFECTION_1_COMPLETED", VarbitID.CA_TASK_HILLGIANT_BOSS_PERFECTION_1_COMPLETED);
		t(l, "CA_TASK_HILLGIANT_BOSS_RESTRICTION_1_COMPLETED", VarbitID.CA_TASK_HILLGIANT_BOSS_RESTRICTION_1_COMPLETED);
		t(l, "CA_TASK_HYDRABOSS_KILLCOUNT_1_COMPLETED", VarbitID.CA_TASK_HYDRABOSS_KILLCOUNT_1_COMPLETED);
		t(l, "CA_TASK_HYDRABOSS_KILLCOUNT_2_COMPLETED", VarbitID.CA_TASK_HYDRABOSS_KILLCOUNT_2_COMPLETED);
		t(l, "CA_TASK_HYDRABOSS_MECHANICAL_1_COMPLETED", VarbitID.CA_TASK_HYDRABOSS_MECHANICAL_1_COMPLETED);
		t(l, "CA_TASK_HYDRABOSS_MECHANICAL_2_COMPLETED", VarbitID.CA_TASK_HYDRABOSS_MECHANICAL_2_COMPLETED);
		t(l, "CA_TASK_HYDRABOSS_MECHANICAL_3_COMPLETED", VarbitID.CA_TASK_HYDRABOSS_MECHANICAL_3_COMPLETED);
		t(l, "CA_TASK_HYDRABOSS_MECHANICAL_4_COMPLETED", VarbitID.CA_TASK_HYDRABOSS_MECHANICAL_4_COMPLETED);
		t(l, "CA_TASK_HYDRABOSS_MECHANICAL_5_COMPLETED", VarbitID.CA_TASK_HYDRABOSS_MECHANICAL_5_COMPLETED);
		t(l, "CA_TASK_HYDRABOSS_PERFECTION_1_COMPLETED", VarbitID.CA_TASK_HYDRABOSS_PERFECTION_1_COMPLETED);
		t(l, "CA_TASK_HYDRABOSS_RESTRICTION_1_COMPLETED", VarbitID.CA_TASK_HYDRABOSS_RESTRICTION_1_COMPLETED);
		t(l, "CA_TASK_HYDRABOSS_SPEED_1_COMPLETED", VarbitID.CA_TASK_HYDRABOSS_SPEED_1_COMPLETED);
		t(l, "CA_TASK_HYDRABOSS_SPEED_2_COMPLETED", VarbitID.CA_TASK_HYDRABOSS_SPEED_2_COMPLETED);
		t(l, "CA_TASK_HYDRABOSS_STAMINA_1_COMPLETED", VarbitID.CA_TASK_HYDRABOSS_STAMINA_1_COMPLETED);
		t(l, "CA_TASK_JAD_KILLCOUNT_1_COMPLETED", VarbitID.CA_TASK_JAD_KILLCOUNT_1_COMPLETED);
		t(l, "CA_TASK_JAD_KILLCOUNT_2_COMPLETED", VarbitID.CA_TASK_JAD_KILLCOUNT_2_COMPLETED);
		t(l, "CA_TASK_JAD_MECHANICAL_1_COMPLETED", VarbitID.CA_TASK_JAD_MECHANICAL_1_COMPLETED);
		t(l, "CA_TASK_JAD_MECHANICAL_2_COMPLETED", VarbitID.CA_TASK_JAD_MECHANICAL_2_COMPLETED);
		t(l, "CA_TASK_JAD_MECHANICAL_3_COMPLETED", VarbitID.CA_TASK_JAD_MECHANICAL_3_COMPLETED);
		t(l, "CA_TASK_JAD_MECHANICAL_4_COMPLETED", VarbitID.CA_TASK_JAD_MECHANICAL_4_COMPLETED);
		t(l, "CA_TASK_JAD_RESTRICTION_1_COMPLETED", VarbitID.CA_TASK_JAD_RESTRICTION_1_COMPLETED);
		t(l, "CA_TASK_JAD_RESTRICTION_2_COMPLETED", VarbitID.CA_TASK_JAD_RESTRICTION_2_COMPLETED);
		t(l, "CA_TASK_JAD_SPEED_1_COMPLETED", VarbitID.CA_TASK_JAD_SPEED_1_COMPLETED);
		t(l, "CA_TASK_JAD_SPEED_2_COMPLETED", VarbitID.CA_TASK_JAD_SPEED_2_COMPLETED);
		t(l, "CA_TASK_KALPHITE_KILLCOUNT_1_COMPLETED", VarbitID.CA_TASK_KALPHITE_KILLCOUNT_1_COMPLETED);
		t(l, "CA_TASK_KALPHITE_KILLCOUNT_2_COMPLETED", VarbitID.CA_TASK_KALPHITE_KILLCOUNT_2_COMPLETED);
		t(l, "CA_TASK_KALPHITE_MECHANICAL_1_COMPLETED", VarbitID.CA_TASK_KALPHITE_MECHANICAL_1_COMPLETED);
		t(l, "CA_TASK_KALPHITE_MECHANICAL_2_COMPLETED", VarbitID.CA_TASK_KALPHITE_MECHANICAL_2_COMPLETED);
		t(l, "CA_TASK_KALPHITE_RESTRICTION_1_COMPLETED", VarbitID.CA_TASK_KALPHITE_RESTRICTION_1_COMPLETED);
		t(l, "CA_TASK_KBD_KILLCOUNT_1_COMPLETED", VarbitID.CA_TASK_KBD_KILLCOUNT_1_COMPLETED);
		t(l, "CA_TASK_KBD_KILLCOUNT_2_COMPLETED", VarbitID.CA_TASK_KBD_KILLCOUNT_2_COMPLETED);
		t(l, "CA_TASK_KBD_MECHANICAL_1_COMPLETED", VarbitID.CA_TASK_KBD_MECHANICAL_1_COMPLETED);
		t(l, "CA_TASK_KBD_RESTRICTION_1_COMPLETED", VarbitID.CA_TASK_KBD_RESTRICTION_1_COMPLETED);
		t(l, "CA_TASK_KBD_RESTRICTION_2_COMPLETED", VarbitID.CA_TASK_KBD_RESTRICTION_2_COMPLETED);
		t(l, "CA_TASK_KBD_STAMINA_1_COMPLETED", VarbitID.CA_TASK_KBD_STAMINA_1_COMPLETED);
		t(l, "CA_TASK_KRAKEN_BOSS_KILLCOUNT_1_COMPLETED", VarbitID.CA_TASK_KRAKEN_BOSS_KILLCOUNT_1_COMPLETED);
		t(l, "CA_TASK_KRAKEN_BOSS_MECHANICAL_1_COMPLETED", VarbitID.CA_TASK_KRAKEN_BOSS_MECHANICAL_1_COMPLETED);
		t(l, "CA_TASK_KRAKEN_BOSS_STAMINA_1_COMPLETED", VarbitID.CA_TASK_KRAKEN_BOSS_STAMINA_1_COMPLETED);
		t(l, "CA_TASK_KURASK_KILLCOUNT_1_COMPLETED", VarbitID.CA_TASK_KURASK_KILLCOUNT_1_COMPLETED);
		t(l, "CA_TASK_LIZARDMAN_SHAMAN_KILLCOUNT_1_COMPLETED", VarbitID.CA_TASK_LIZARDMAN_SHAMAN_KILLCOUNT_1_COMPLETED);
		t(l, "CA_TASK_MIMIC_KILLCOUNT_1_COMPLETED", VarbitID.CA_TASK_MIMIC_KILLCOUNT_1_COMPLETED);
		t(l, "CA_TASK_MOLE_KILLCOUNT_1_COMPLETED", VarbitID.CA_TASK_MOLE_KILLCOUNT_1_COMPLETED);
		t(l, "CA_TASK_MOLE_KILLCOUNT_2_COMPLETED", VarbitID.CA_TASK_MOLE_KILLCOUNT_2_COMPLETED);
		t(l, "CA_TASK_MOLE_MECHANICAL_1_COMPLETED", VarbitID.CA_TASK_MOLE_MECHANICAL_1_COMPLETED);
		t(l, "CA_TASK_MOLE_MECHANICAL_2_COMPLETED", VarbitID.CA_TASK_MOLE_MECHANICAL_2_COMPLETED);
		t(l, "CA_TASK_MOLE_MECHANICAL_3_COMPLETED", VarbitID.CA_TASK_MOLE_MECHANICAL_3_COMPLETED);
		t(l, "CA_TASK_MOLE_PERFECTION_1_COMPLETED", VarbitID.CA_TASK_MOLE_PERFECTION_1_COMPLETED);
		t(l, "CA_TASK_NIGHTMARE_KILLCOUNT_1_COMPLETED", VarbitID.CA_TASK_NIGHTMARE_KILLCOUNT_1_COMPLETED);
		t(l, "CA_TASK_NIGHTMARE_KILLCOUNT_2_COMPLETED", VarbitID.CA_TASK_NIGHTMARE_KILLCOUNT_2_COMPLETED);
		t(l, "CA_TASK_NIGHTMARE_KILLCOUNT_3_COMPLETED", VarbitID.CA_TASK_NIGHTMARE_KILLCOUNT_3_COMPLETED);
		t(l, "CA_TASK_NIGHTMARE_MECHANICAL_1_COMPLETED", VarbitID.CA_TASK_NIGHTMARE_MECHANICAL_1_COMPLETED);
		t(l, "CA_TASK_NIGHTMARE_MECHANICAL_2_COMPLETED", VarbitID.CA_TASK_NIGHTMARE_MECHANICAL_2_COMPLETED);
		t(l, "CA_TASK_NIGHTMARE_PERFECTION_1_COMPLETED", VarbitID.CA_TASK_NIGHTMARE_PERFECTION_1_COMPLETED);
		t(l, "CA_TASK_NIGHTMARE_RESTRICTION_1_COMPLETED", VarbitID.CA_TASK_NIGHTMARE_RESTRICTION_1_COMPLETED);
		t(l, "CA_TASK_NIGHTMARE_RESTRICTION_2_COMPLETED", VarbitID.CA_TASK_NIGHTMARE_RESTRICTION_2_COMPLETED);
		t(l, "CA_TASK_NIGHTMARE_SPEED_1_COMPLETED", VarbitID.CA_TASK_NIGHTMARE_SPEED_1_COMPLETED);
		t(l, "CA_TASK_NIGHTMARE_SPEED_2_COMPLETED", VarbitID.CA_TASK_NIGHTMARE_SPEED_2_COMPLETED);
		t(l, "CA_TASK_NIGHTMARE_SPEED_3_COMPLETED", VarbitID.CA_TASK_NIGHTMARE_SPEED_3_COMPLETED);
		t(l, "CA_TASK_NIGHTMARE_SPEED_4_COMPLETED", VarbitID.CA_TASK_NIGHTMARE_SPEED_4_COMPLETED);
		t(l, "CA_TASK_NIGHTMARE_SPEED_5_COMPLETED", VarbitID.CA_TASK_NIGHTMARE_SPEED_5_COMPLETED);
		t(l, "CA_TASK_NIGHTMARE_SPEED_6_COMPLETED", VarbitID.CA_TASK_NIGHTMARE_SPEED_6_COMPLETED);
		t(l, "CA_TASK_PRIME_KILLCOUNT_1_COMPLETED", VarbitID.CA_TASK_PRIME_KILLCOUNT_1_COMPLETED);
		t(l, "CA_TASK_PRIME_KILLCOUNT_2_COMPLETED", VarbitID.CA_TASK_PRIME_KILLCOUNT_2_COMPLETED);
		t(l, "CA_TASK_PRIME_MECHANICAL_1_COMPLETED", VarbitID.CA_TASK_PRIME_MECHANICAL_1_COMPLETED);
		t(l, "CA_TASK_PRIME_MECHANICAL_2_COMPLETED", VarbitID.CA_TASK_PRIME_MECHANICAL_2_COMPLETED);
		t(l, "CA_TASK_REX_KILLCOUNT_1_COMPLETED", VarbitID.CA_TASK_REX_KILLCOUNT_1_COMPLETED);
		t(l, "CA_TASK_REX_KILLCOUNT_2_COMPLETED", VarbitID.CA_TASK_REX_KILLCOUNT_2_COMPLETED);
		t(l, "CA_TASK_REX_MECHANICAL_1_COMPLETED", VarbitID.CA_TASK_REX_MECHANICAL_1_COMPLETED);
		t(l, "CA_TASK_REX_MECHANICAL_2_COMPLETED", VarbitID.CA_TASK_REX_MECHANICAL_2_COMPLETED);
		t(l, "CA_TASK_REX_MECHANICAL_3_COMPLETED", VarbitID.CA_TASK_REX_MECHANICAL_3_COMPLETED);
		t(l, "CA_TASK_SARACHNIS_KILLCOUNT_1_COMPLETED", VarbitID.CA_TASK_SARACHNIS_KILLCOUNT_1_COMPLETED);
		t(l, "CA_TASK_SARACHNIS_KILLCOUNT_2_COMPLETED", VarbitID.CA_TASK_SARACHNIS_KILLCOUNT_2_COMPLETED);
		t(l, "CA_TASK_SARACHNIS_MECHANICAL_1_COMPLETED", VarbitID.CA_TASK_SARACHNIS_MECHANICAL_1_COMPLETED);
		t(l, "CA_TASK_SARACHNIS_PERFECTION_1_COMPLETED", VarbitID.CA_TASK_SARACHNIS_PERFECTION_1_COMPLETED);
		t(l, "CA_TASK_SARACHNIS_RESTRICTION_1_COMPLETED", VarbitID.CA_TASK_SARACHNIS_RESTRICTION_1_COMPLETED);
		t(l, "CA_TASK_SARADOMIN_KILLCOUNT_1_COMPLETED", VarbitID.CA_TASK_SARADOMIN_KILLCOUNT_1_COMPLETED);
		t(l, "CA_TASK_SARADOMIN_KILLCOUNT_2_COMPLETED", VarbitID.CA_TASK_SARADOMIN_KILLCOUNT_2_COMPLETED);
		t(l, "CA_TASK_SARADOMIN_MECHANICAL_1_COMPLETED", VarbitID.CA_TASK_SARADOMIN_MECHANICAL_1_COMPLETED);
		t(l, "CA_TASK_SARADOMIN_PERFECTION_1_COMPLETED", VarbitID.CA_TASK_SARADOMIN_PERFECTION_1_COMPLETED);
		t(l, "CA_TASK_SARADOMIN_RESTRICTION_1_COMPLETED", VarbitID.CA_TASK_SARADOMIN_RESTRICTION_1_COMPLETED);
		t(l, "CA_TASK_SARADOMIN_RESTRICTION_2_COMPLETED", VarbitID.CA_TASK_SARADOMIN_RESTRICTION_2_COMPLETED);
		t(l, "CA_TASK_SARADOMIN_STAMINA_1_COMPLETED", VarbitID.CA_TASK_SARADOMIN_STAMINA_1_COMPLETED);
		t(l, "CA_TASK_SCORPIA_KILLCOUNT_1_COMPLETED", VarbitID.CA_TASK_SCORPIA_KILLCOUNT_1_COMPLETED);
		t(l, "CA_TASK_SCORPIA_KILLCOUNT_2_COMPLETED", VarbitID.CA_TASK_SCORPIA_KILLCOUNT_2_COMPLETED);
		t(l, "CA_TASK_SCORPIA_PERFECTION_1_COMPLETED", VarbitID.CA_TASK_SCORPIA_PERFECTION_1_COMPLETED);
		t(l, "CA_TASK_SCORPIA_RESTRICTION_1_COMPLETED", VarbitID.CA_TASK_SCORPIA_RESTRICTION_1_COMPLETED);
		t(l, "CA_TASK_SEREN_SPEED_1_COMPLETED", VarbitID.CA_TASK_SEREN_SPEED_1_COMPLETED);
		t(l, "CA_TASK_SKELETAL_WYVERN_KILLCOUNT_1_COMPLETED", VarbitID.CA_TASK_SKELETAL_WYVERN_KILLCOUNT_1_COMPLETED);
		t(l, "CA_TASK_SNAKEBOSS_KILLCOUNT_1_COMPLETED", VarbitID.CA_TASK_SNAKEBOSS_KILLCOUNT_1_COMPLETED);
		t(l, "CA_TASK_SNAKEBOSS_KILLCOUNT_2_COMPLETED", VarbitID.CA_TASK_SNAKEBOSS_KILLCOUNT_2_COMPLETED);
		t(l, "CA_TASK_SNAKEBOSS_KILLCOUNT_3_COMPLETED", VarbitID.CA_TASK_SNAKEBOSS_KILLCOUNT_3_COMPLETED);
		t(l, "CA_TASK_SNAKEBOSS_MECHANICAL_1_COMPLETED", VarbitID.CA_TASK_SNAKEBOSS_MECHANICAL_1_COMPLETED);
		t(l, "CA_TASK_SNAKEBOSS_MECHANICAL_2_COMPLETED", VarbitID.CA_TASK_SNAKEBOSS_MECHANICAL_2_COMPLETED);
		t(l, "CA_TASK_SNAKEBOSS_PERFECTION_1_COMPLETED", VarbitID.CA_TASK_SNAKEBOSS_PERFECTION_1_COMPLETED);
		t(l, "CA_TASK_SNAKEBOSS_SPEED_1_COMPLETED", VarbitID.CA_TASK_SNAKEBOSS_SPEED_1_COMPLETED);
		t(l, "CA_TASK_SNAKEBOSS_SPEED_2_COMPLETED", VarbitID.CA_TASK_SNAKEBOSS_SPEED_2_COMPLETED);
		t(l, "CA_TASK_SNAKEBOSS_SPEED_3_COMPLETED", VarbitID.CA_TASK_SNAKEBOSS_SPEED_3_COMPLETED);
		t(l, "CA_TASK_SUPREME_KILLCOUNT_1_COMPLETED", VarbitID.CA_TASK_SUPREME_KILLCOUNT_1_COMPLETED);
		t(l, "CA_TASK_SUPREME_KILLCOUNT_2_COMPLETED", VarbitID.CA_TASK_SUPREME_KILLCOUNT_2_COMPLETED);
		t(l, "CA_TASK_SUPREME_MECHANICAL_1_COMPLETED", VarbitID.CA_TASK_SUPREME_MECHANICAL_1_COMPLETED);
		t(l, "CA_TASK_SUPREME_MECHANICAL_2_COMPLETED", VarbitID.CA_TASK_SUPREME_MECHANICAL_2_COMPLETED);
		t(l, "CA_TASK_THEATREOFBLOOD_KILLCOUNT_1_COMPLETED", VarbitID.CA_TASK_THEATREOFBLOOD_KILLCOUNT_1_COMPLETED);
		t(l, "CA_TASK_THEATREOFBLOOD_KILLCOUNT_2_COMPLETED", VarbitID.CA_TASK_THEATREOFBLOOD_KILLCOUNT_2_COMPLETED);
		t(l, "CA_TASK_THEATREOFBLOOD_KILLCOUNT_3_COMPLETED", VarbitID.CA_TASK_THEATREOFBLOOD_KILLCOUNT_3_COMPLETED);
		t(l, "CA_TASK_THEATREOFBLOOD_MECHANICAL_1_COMPLETED", VarbitID.CA_TASK_THEATREOFBLOOD_MECHANICAL_1_COMPLETED);
		t(l, "CA_TASK_THEATREOFBLOOD_MECHANICAL_2_COMPLETED", VarbitID.CA_TASK_THEATREOFBLOOD_MECHANICAL_2_COMPLETED);
		t(l, "CA_TASK_THEATREOFBLOOD_MECHANICAL_3_COMPLETED", VarbitID.CA_TASK_THEATREOFBLOOD_MECHANICAL_3_COMPLETED);
		t(l, "CA_TASK_THEATREOFBLOOD_PERFECTION_1_COMPLETED", VarbitID.CA_TASK_THEATREOFBLOOD_PERFECTION_1_COMPLETED);
		t(l, "CA_TASK_THEATREOFBLOOD_PERFECTION_2_COMPLETED", VarbitID.CA_TASK_THEATREOFBLOOD_PERFECTION_2_COMPLETED);
		t(l, "CA_TASK_THEATREOFBLOOD_PERFECTION_3_COMPLETED", VarbitID.CA_TASK_THEATREOFBLOOD_PERFECTION_3_COMPLETED);
		t(l, "CA_TASK_THEATREOFBLOOD_PERFECTION_4_COMPLETED", VarbitID.CA_TASK_THEATREOFBLOOD_PERFECTION_4_COMPLETED);
		t(l, "CA_TASK_THEATREOFBLOOD_PERFECTION_5_COMPLETED", VarbitID.CA_TASK_THEATREOFBLOOD_PERFECTION_5_COMPLETED);
		t(l, "CA_TASK_THEATREOFBLOOD_PERFECTION_6_COMPLETED", VarbitID.CA_TASK_THEATREOFBLOOD_PERFECTION_6_COMPLETED);
		t(l, "CA_TASK_THEATREOFBLOOD_PERFECTION_7_COMPLETED", VarbitID.CA_TASK_THEATREOFBLOOD_PERFECTION_7_COMPLETED);
		t(l, "CA_TASK_THEATREOFBLOOD_RESTRICTION_1_COMPLETED", VarbitID.CA_TASK_THEATREOFBLOOD_RESTRICTION_1_COMPLETED);
		t(l, "CA_TASK_THEATREOFBLOOD_RESTRICTION_2_COMPLETED", VarbitID.CA_TASK_THEATREOFBLOOD_RESTRICTION_2_COMPLETED);
		t(l, "CA_TASK_THEATREOFBLOOD_RESTRICTION_3_COMPLETED", VarbitID.CA_TASK_THEATREOFBLOOD_RESTRICTION_3_COMPLETED);
		t(l, "CA_TASK_THEATREOFBLOOD_RESTRICTION_4_COMPLETED", VarbitID.CA_TASK_THEATREOFBLOOD_RESTRICTION_4_COMPLETED);
		t(l, "CA_TASK_THEATREOFBLOOD_SPEED_1_COMPLETED", VarbitID.CA_TASK_THEATREOFBLOOD_SPEED_1_COMPLETED);
		t(l, "CA_TASK_THEATREOFBLOOD_SPEED_2_COMPLETED", VarbitID.CA_TASK_THEATREOFBLOOD_SPEED_2_COMPLETED);
		t(l, "CA_TASK_THEATREOFBLOOD_SPEED_3_COMPLETED", VarbitID.CA_TASK_THEATREOFBLOOD_SPEED_3_COMPLETED);
		t(l, "CA_TASK_THEATREOFBLOOD_SPEED_4_COMPLETED", VarbitID.CA_TASK_THEATREOFBLOOD_SPEED_4_COMPLETED);
		t(l, "CA_TASK_THEATREOFBLOOD_SPEED_5_COMPLETED", VarbitID.CA_TASK_THEATREOFBLOOD_SPEED_5_COMPLETED);
		t(l, "CA_TASK_THEATREOFBLOOD_SPEED_6_COMPLETED", VarbitID.CA_TASK_THEATREOFBLOOD_SPEED_6_COMPLETED);
		t(l, "CA_TASK_THEATREOFBLOOD_SPEED_7_COMPLETED", VarbitID.CA_TASK_THEATREOFBLOOD_SPEED_7_COMPLETED);
		t(l, "CA_TASK_THERMY_KILLCOUNT_1_COMPLETED", VarbitID.CA_TASK_THERMY_KILLCOUNT_1_COMPLETED);
		t(l, "CA_TASK_THERMY_PERFECTION_1_COMPLETED", VarbitID.CA_TASK_THERMY_PERFECTION_1_COMPLETED);
		t(l, "CA_TASK_THERMY_RESTRICTION_2_COMPLETED", VarbitID.CA_TASK_THERMY_RESTRICTION_2_COMPLETED);
		t(l, "CA_TASK_VENENATIS_KILLCOUNT_1_COMPLETED", VarbitID.CA_TASK_VENENATIS_KILLCOUNT_1_COMPLETED);
		t(l, "CA_TASK_VENENATIS_KILLCOUNT_2_COMPLETED", VarbitID.CA_TASK_VENENATIS_KILLCOUNT_2_COMPLETED);
		t(l, "CA_TASK_VETION_KILLCOUNT_1_COMPLETED", VarbitID.CA_TASK_VETION_KILLCOUNT_1_COMPLETED);
		t(l, "CA_TASK_VETION_KILLCOUNT_2_COMPLETED", VarbitID.CA_TASK_VETION_KILLCOUNT_2_COMPLETED);
		t(l, "CA_TASK_VORKATH_KILLCOUNT_1_COMPLETED", VarbitID.CA_TASK_VORKATH_KILLCOUNT_1_COMPLETED);
		t(l, "CA_TASK_VORKATH_KILLCOUNT_2_COMPLETED", VarbitID.CA_TASK_VORKATH_KILLCOUNT_2_COMPLETED);
		t(l, "CA_TASK_VORKATH_MECHANICAL_1_COMPLETED", VarbitID.CA_TASK_VORKATH_MECHANICAL_1_COMPLETED);
		t(l, "CA_TASK_VORKATH_MECHANICAL_2_COMPLETED", VarbitID.CA_TASK_VORKATH_MECHANICAL_2_COMPLETED);
		t(l, "CA_TASK_VORKATH_PERFECTION_1_COMPLETED", VarbitID.CA_TASK_VORKATH_PERFECTION_1_COMPLETED);
		t(l, "CA_TASK_VORKATH_RESTRICTION_1_COMPLETED", VarbitID.CA_TASK_VORKATH_RESTRICTION_1_COMPLETED);
		t(l, "CA_TASK_VORKATH_RESTRICTION_2_COMPLETED", VarbitID.CA_TASK_VORKATH_RESTRICTION_2_COMPLETED);
		t(l, "CA_TASK_VORKATH_RESTRICTION_3_COMPLETED", VarbitID.CA_TASK_VORKATH_RESTRICTION_3_COMPLETED);
		t(l, "CA_TASK_VORKATH_SPEED_1_COMPLETED", VarbitID.CA_TASK_VORKATH_SPEED_1_COMPLETED);
		t(l, "CA_TASK_VORKATH_SPEED_2_COMPLETED", VarbitID.CA_TASK_VORKATH_SPEED_2_COMPLETED);
		t(l, "CA_TASK_VORKATH_STAMINA_1_COMPLETED", VarbitID.CA_TASK_VORKATH_STAMINA_1_COMPLETED);
		t(l, "CA_TASK_WINTERTODT_KILLCOUNT_1_COMPLETED", VarbitID.CA_TASK_WINTERTODT_KILLCOUNT_1_COMPLETED);
		t(l, "CA_TASK_WINTERTODT_KILLCOUNT_2_COMPLETED", VarbitID.CA_TASK_WINTERTODT_KILLCOUNT_2_COMPLETED);
		t(l, "CA_TASK_WINTERTODT_MECHANICAL_1_COMPLETED", VarbitID.CA_TASK_WINTERTODT_MECHANICAL_1_COMPLETED);
		t(l, "CA_TASK_WINTERTODT_MECHANICAL_2_COMPLETED", VarbitID.CA_TASK_WINTERTODT_MECHANICAL_2_COMPLETED);
		t(l, "CA_TASK_WINTERTODT_PERFECTION_1_COMPLETED", VarbitID.CA_TASK_WINTERTODT_PERFECTION_1_COMPLETED);
		t(l, "CA_TASK_WINTERTODT_PERFECTION_2_COMPLETED", VarbitID.CA_TASK_WINTERTODT_PERFECTION_2_COMPLETED);
		t(l, "CA_TASK_WINTERTODT_RESTRICTION_1_COMPLETED", VarbitID.CA_TASK_WINTERTODT_RESTRICTION_1_COMPLETED);
		t(l, "CA_TASK_WINTERTODT_STAMINA_1_COMPLETED", VarbitID.CA_TASK_WINTERTODT_STAMINA_1_COMPLETED);
		t(l, "CA_TASK_WYRM_KILLCOUNT_1_COMPLETED", VarbitID.CA_TASK_WYRM_KILLCOUNT_1_COMPLETED);
		t(l, "CA_TASK_XERICCHAMBERS_CHALLENGE_KILLCOUNT_1_COMPLETED", VarbitID.CA_TASK_XERICCHAMBERS_CHALLENGE_KILLCOUNT_1_COMPLETED);
		t(l, "CA_TASK_XERICCHAMBERS_CHALLENGE_KILLCOUNT_2_COMPLETED", VarbitID.CA_TASK_XERICCHAMBERS_CHALLENGE_KILLCOUNT_2_COMPLETED);
		t(l, "CA_TASK_XERICCHAMBERS_CHALLENGE_PERFECTION_1_COMPLETED", VarbitID.CA_TASK_XERICCHAMBERS_CHALLENGE_PERFECTION_1_COMPLETED);
		t(l, "CA_TASK_XERICCHAMBERS_CHALLENGE_PERFECTION_2_COMPLETED", VarbitID.CA_TASK_XERICCHAMBERS_CHALLENGE_PERFECTION_2_COMPLETED);
		t(l, "CA_TASK_XERICCHAMBERS_CHALLENGE_SPEED_1_COMPLETED", VarbitID.CA_TASK_XERICCHAMBERS_CHALLENGE_SPEED_1_COMPLETED);
		t(l, "CA_TASK_XERICCHAMBERS_CHALLENGE_SPEED_2_COMPLETED", VarbitID.CA_TASK_XERICCHAMBERS_CHALLENGE_SPEED_2_COMPLETED);
		t(l, "CA_TASK_XERICCHAMBERS_CHALLENGE_SPEED_3_COMPLETED", VarbitID.CA_TASK_XERICCHAMBERS_CHALLENGE_SPEED_3_COMPLETED);
		t(l, "CA_TASK_XERICCHAMBERS_CHALLENGE_SPEED_4_COMPLETED", VarbitID.CA_TASK_XERICCHAMBERS_CHALLENGE_SPEED_4_COMPLETED);
		t(l, "CA_TASK_XERICCHAMBERS_CHALLENGE_SPEED_5_COMPLETED", VarbitID.CA_TASK_XERICCHAMBERS_CHALLENGE_SPEED_5_COMPLETED);
		t(l, "CA_TASK_XERICCHAMBERS_CHALLENGE_SPEED_6_COMPLETED", VarbitID.CA_TASK_XERICCHAMBERS_CHALLENGE_SPEED_6_COMPLETED);
		t(l, "CA_TASK_XERICCHAMBERS_CHALLENGE_SPEED_7_COMPLETED", VarbitID.CA_TASK_XERICCHAMBERS_CHALLENGE_SPEED_7_COMPLETED);
		t(l, "CA_TASK_XERICCHAMBERS_KILLCOUNT_1_COMPLETED", VarbitID.CA_TASK_XERICCHAMBERS_KILLCOUNT_1_COMPLETED);
		t(l, "CA_TASK_XERICCHAMBERS_KILLCOUNT_2_COMPLETED", VarbitID.CA_TASK_XERICCHAMBERS_KILLCOUNT_2_COMPLETED);
		t(l, "CA_TASK_XERICCHAMBERS_KILLCOUNT_3_COMPLETED", VarbitID.CA_TASK_XERICCHAMBERS_KILLCOUNT_3_COMPLETED);
		t(l, "CA_TASK_XERICCHAMBERS_MECHANICAL_1_COMPLETED", VarbitID.CA_TASK_XERICCHAMBERS_MECHANICAL_1_COMPLETED);
		t(l, "CA_TASK_XERICCHAMBERS_MECHANICAL_2_COMPLETED", VarbitID.CA_TASK_XERICCHAMBERS_MECHANICAL_2_COMPLETED);
		t(l, "CA_TASK_XERICCHAMBERS_MECHANICAL_3_COMPLETED", VarbitID.CA_TASK_XERICCHAMBERS_MECHANICAL_3_COMPLETED);
		t(l, "CA_TASK_XERICCHAMBERS_MECHANICAL_4_COMPLETED", VarbitID.CA_TASK_XERICCHAMBERS_MECHANICAL_4_COMPLETED);
		t(l, "CA_TASK_XERICCHAMBERS_MECHANICAL_5_COMPLETED", VarbitID.CA_TASK_XERICCHAMBERS_MECHANICAL_5_COMPLETED);
		t(l, "CA_TASK_XERICCHAMBERS_MECHANICAL_6_COMPLETED", VarbitID.CA_TASK_XERICCHAMBERS_MECHANICAL_6_COMPLETED);
		t(l, "CA_TASK_XERICCHAMBERS_MECHANICAL_7_COMPLETED", VarbitID.CA_TASK_XERICCHAMBERS_MECHANICAL_7_COMPLETED);
		t(l, "CA_TASK_XERICCHAMBERS_MECHANICAL_8_COMPLETED", VarbitID.CA_TASK_XERICCHAMBERS_MECHANICAL_8_COMPLETED);
		t(l, "CA_TASK_XERICCHAMBERS_MECHANICAL_9_COMPLETED", VarbitID.CA_TASK_XERICCHAMBERS_MECHANICAL_9_COMPLETED);
		t(l, "CA_TASK_XERICCHAMBERS_PERFECTION_1_COMPLETED", VarbitID.CA_TASK_XERICCHAMBERS_PERFECTION_1_COMPLETED);
		t(l, "CA_TASK_XERICCHAMBERS_PERFECTION_2_COMPLETED", VarbitID.CA_TASK_XERICCHAMBERS_PERFECTION_2_COMPLETED);
		t(l, "CA_TASK_XERICCHAMBERS_PERFECTION_3_COMPLETED", VarbitID.CA_TASK_XERICCHAMBERS_PERFECTION_3_COMPLETED);
		t(l, "CA_TASK_XERICCHAMBERS_PERFECTION_4_COMPLETED", VarbitID.CA_TASK_XERICCHAMBERS_PERFECTION_4_COMPLETED);
		t(l, "CA_TASK_XERICCHAMBERS_PERFECTION_5_COMPLETED", VarbitID.CA_TASK_XERICCHAMBERS_PERFECTION_5_COMPLETED);
		t(l, "CA_TASK_XERICCHAMBERS_PERFECTION_6_COMPLETED", VarbitID.CA_TASK_XERICCHAMBERS_PERFECTION_6_COMPLETED);
		t(l, "CA_TASK_XERICCHAMBERS_PERFECTION_7_COMPLETED", VarbitID.CA_TASK_XERICCHAMBERS_PERFECTION_7_COMPLETED);
		t(l, "CA_TASK_XERICCHAMBERS_PERFECTION_8_COMPLETED", VarbitID.CA_TASK_XERICCHAMBERS_PERFECTION_8_COMPLETED);
		t(l, "CA_TASK_XERICCHAMBERS_PERFECTION_9_COMPLETED", VarbitID.CA_TASK_XERICCHAMBERS_PERFECTION_9_COMPLETED);
		t(l, "CA_TASK_XERICCHAMBERS_RESTRICTION_1_COMPLETED", VarbitID.CA_TASK_XERICCHAMBERS_RESTRICTION_1_COMPLETED);
		t(l, "CA_TASK_XERICCHAMBERS_RESTRICTION_2_COMPLETED", VarbitID.CA_TASK_XERICCHAMBERS_RESTRICTION_2_COMPLETED);
		t(l, "CA_TASK_XERICCHAMBERS_SPEED_1_COMPLETED", VarbitID.CA_TASK_XERICCHAMBERS_SPEED_1_COMPLETED);
		t(l, "CA_TASK_XERICCHAMBERS_SPEED_2_COMPLETED", VarbitID.CA_TASK_XERICCHAMBERS_SPEED_2_COMPLETED);
		t(l, "CA_TASK_XERICCHAMBERS_SPEED_3_COMPLETED", VarbitID.CA_TASK_XERICCHAMBERS_SPEED_3_COMPLETED);
		t(l, "CA_TASK_XERICCHAMBERS_SPEED_4_COMPLETED", VarbitID.CA_TASK_XERICCHAMBERS_SPEED_4_COMPLETED);
		t(l, "CA_TASK_XERICCHAMBERS_SPEED_5_COMPLETED", VarbitID.CA_TASK_XERICCHAMBERS_SPEED_5_COMPLETED);
		t(l, "CA_TASK_XERICCHAMBERS_SPEED_6_COMPLETED", VarbitID.CA_TASK_XERICCHAMBERS_SPEED_6_COMPLETED);
		t(l, "CA_TASK_ZALCANO_KILLCOUNT_1_COMPLETED", VarbitID.CA_TASK_ZALCANO_KILLCOUNT_1_COMPLETED);
		t(l, "CA_TASK_ZALCANO_PERFECTION_1_COMPLETED", VarbitID.CA_TASK_ZALCANO_PERFECTION_1_COMPLETED);
		t(l, "CA_TASK_ZALCANO_MECHANICAL_1_COMPLETED", VarbitID.CA_TASK_ZALCANO_MECHANICAL_1_COMPLETED);
		t(l, "CA_TASK_ZALCANO_MECHANICAL_2_COMPLETED", VarbitID.CA_TASK_ZALCANO_MECHANICAL_2_COMPLETED);
		t(l, "CA_TASK_ZAMORAK_KILLCOUNT_1_COMPLETED", VarbitID.CA_TASK_ZAMORAK_KILLCOUNT_1_COMPLETED);
		t(l, "CA_TASK_ZAMORAK_KILLCOUNT_2_COMPLETED", VarbitID.CA_TASK_ZAMORAK_KILLCOUNT_2_COMPLETED);
		t(l, "CA_TASK_ZAMORAK_MECHANICAL_1_COMPLETED", VarbitID.CA_TASK_ZAMORAK_MECHANICAL_1_COMPLETED);
		t(l, "CA_TASK_ZAMORAK_MECHANICAL_2_COMPLETED", VarbitID.CA_TASK_ZAMORAK_MECHANICAL_2_COMPLETED);
		t(l, "CA_TASK_ZAMORAK_MECHANICAL_3_COMPLETED", VarbitID.CA_TASK_ZAMORAK_MECHANICAL_3_COMPLETED);
		t(l, "CA_TASK_ZAMORAK_PERFECTION_1_COMPLETED", VarbitID.CA_TASK_ZAMORAK_PERFECTION_1_COMPLETED);
		t(l, "CA_TASK_ZAMORAK_PERFECTION_2_COMPLETED", VarbitID.CA_TASK_ZAMORAK_PERFECTION_2_COMPLETED);
		t(l, "CA_TASK_ZAMORAK_RESTRICTION_1_COMPLETED", VarbitID.CA_TASK_ZAMORAK_RESTRICTION_1_COMPLETED);
		t(l, "CA_TASK_ZAMORAK_STAMINA_1_COMPLETED", VarbitID.CA_TASK_ZAMORAK_STAMINA_1_COMPLETED);
		t(l, "CA_TASK_ZUK_KILLCOUNT_1_COMPLETED", VarbitID.CA_TASK_ZUK_KILLCOUNT_1_COMPLETED);
		t(l, "CA_TASK_ZUK_KILLCOUNT_3_COMPLETED", VarbitID.CA_TASK_ZUK_KILLCOUNT_3_COMPLETED);
		t(l, "CA_TASK_ZUK_MECHANICAL_1_COMPLETED", VarbitID.CA_TASK_ZUK_MECHANICAL_1_COMPLETED);
		t(l, "CA_TASK_ZUK_MECHANICAL_2_COMPLETED", VarbitID.CA_TASK_ZUK_MECHANICAL_2_COMPLETED);
		t(l, "CA_TASK_ZUK_PERFECTION_1_COMPLETED", VarbitID.CA_TASK_ZUK_PERFECTION_1_COMPLETED);
		t(l, "CA_TASK_ZUK_PERFECTION_2_COMPLETED", VarbitID.CA_TASK_ZUK_PERFECTION_2_COMPLETED);
		t(l, "CA_TASK_ZUK_RESTRICTION_1_COMPLETED", VarbitID.CA_TASK_ZUK_RESTRICTION_1_COMPLETED);
		t(l, "CA_TASK_ZUK_RESTRICTION_2_COMPLETED", VarbitID.CA_TASK_ZUK_RESTRICTION_2_COMPLETED);
		t(l, "CA_TASK_ZUK_RESTRICTION_3_COMPLETED", VarbitID.CA_TASK_ZUK_RESTRICTION_3_COMPLETED);
		t(l, "CA_TASK_ZUK_RESTRICTION_4_COMPLETED", VarbitID.CA_TASK_ZUK_RESTRICTION_4_COMPLETED);
		t(l, "CA_TASK_ZUK_RESTRICTION_5_COMPLETED", VarbitID.CA_TASK_ZUK_RESTRICTION_5_COMPLETED);
		t(l, "CA_TASK_ZUK_SPEED_1_COMPLETED", VarbitID.CA_TASK_ZUK_SPEED_1_COMPLETED);
		t(l, "CA_TASK_TEMPOROSS_KILLCOUNT_1_COMPLETED", VarbitID.CA_TASK_TEMPOROSS_KILLCOUNT_1_COMPLETED);
		t(l, "CA_TASK_TEMPOROSS_KILLCOUNT_2_COMPLETED", VarbitID.CA_TASK_TEMPOROSS_KILLCOUNT_2_COMPLETED);
		t(l, "CA_TASK_TEMPOROSS_RESTRICTION_1_COMPLETED", VarbitID.CA_TASK_TEMPOROSS_RESTRICTION_1_COMPLETED);
		t(l, "CA_TASK_TEMPOROSS_MECHANICAL_1_COMPLETED", VarbitID.CA_TASK_TEMPOROSS_MECHANICAL_1_COMPLETED);
		t(l, "CA_TASK_TEMPOROSS_MECHANICAL_2_COMPLETED", VarbitID.CA_TASK_TEMPOROSS_MECHANICAL_2_COMPLETED);
		t(l, "CA_TASK_TEMPOROSS_MECHANICAL_3_COMPLETED", VarbitID.CA_TASK_TEMPOROSS_MECHANICAL_3_COMPLETED);
		t(l, "CA_TASK_TEMPOROSS_PERFECTION_0_COMPLETED", VarbitID.CA_TASK_TEMPOROSS_PERFECTION_0_COMPLETED);
		t(l, "CA_TASK_TEMPOROSS_MECHANICAL_4_COMPLETED", VarbitID.CA_TASK_TEMPOROSS_MECHANICAL_4_COMPLETED);
		t(l, "CA_TASK_TZHAARKETRAK_KILLCOUNT_1_COMPLETED", VarbitID.CA_TASK_TZHAARKETRAK_KILLCOUNT_1_COMPLETED);
		t(l, "CA_TASK_TZHAARKETRAK_KILLCOUNT_2_COMPLETED", VarbitID.CA_TASK_TZHAARKETRAK_KILLCOUNT_2_COMPLETED);
		t(l, "CA_TASK_TZHAARKETRAK_KILLCOUNT_3_COMPLETED", VarbitID.CA_TASK_TZHAARKETRAK_KILLCOUNT_3_COMPLETED);
		t(l, "CA_TASK_TZHAARKETRAK_SPEED_1_COMPLETED", VarbitID.CA_TASK_TZHAARKETRAK_SPEED_1_COMPLETED);
		t(l, "CA_TASK_TZHAARKETRAK_SPEED_2_COMPLETED", VarbitID.CA_TASK_TZHAARKETRAK_SPEED_2_COMPLETED);
		t(l, "CA_TASK_TZHAARKETRAK_SPEED_3_COMPLETED", VarbitID.CA_TASK_TZHAARKETRAK_SPEED_3_COMPLETED);
		t(l, "CA_TASK_TZHAARKETRAK_RESTRICTION_1_COMPLETED", VarbitID.CA_TASK_TZHAARKETRAK_RESTRICTION_1_COMPLETED);
		t(l, "CA_TASK_TZHAARKETRAK_RESTRICTION_2_COMPLETED", VarbitID.CA_TASK_TZHAARKETRAK_RESTRICTION_2_COMPLETED);
		t(l, "CA_TASK_TZHAARKETRAK_PERFECTION_1_COMPLETED", VarbitID.CA_TASK_TZHAARKETRAK_PERFECTION_1_COMPLETED);
		t(l, "CA_TASK_TZHAARKETRAK_PERFECTION_2_COMPLETED", VarbitID.CA_TASK_TZHAARKETRAK_PERFECTION_2_COMPLETED);
		t(l, "CA_TASK_TZHAARKETRAK_MECHANICAL_1_COMPLETED", VarbitID.CA_TASK_TZHAARKETRAK_MECHANICAL_1_COMPLETED);
		t(l, "CA_TASK_THEATREOFBLOOD_HARD_MECHANICAL_1_COMPLETED", VarbitID.CA_TASK_THEATREOFBLOOD_HARD_MECHANICAL_1_COMPLETED);
		t(l, "CA_TASK_THEATREOFBLOOD_HARD_MECHANICAL_2_COMPLETED", VarbitID.CA_TASK_THEATREOFBLOOD_HARD_MECHANICAL_2_COMPLETED);
		t(l, "CA_TASK_THEATREOFBLOOD_HARD_MECHANICAL_3_COMPLETED", VarbitID.CA_TASK_THEATREOFBLOOD_HARD_MECHANICAL_3_COMPLETED);
		t(l, "CA_TASK_THEATREOFBLOOD_HARD_MECHANICAL_4_COMPLETED", VarbitID.CA_TASK_THEATREOFBLOOD_HARD_MECHANICAL_4_COMPLETED);
		t(l, "CA_TASK_THEATREOFBLOOD_HARD_MECHANICAL_5_COMPLETED", VarbitID.CA_TASK_THEATREOFBLOOD_HARD_MECHANICAL_5_COMPLETED);
		t(l, "CA_TASK_THEATREOFBLOOD_HARD_PERFECTION_1_COMPLETED", VarbitID.CA_TASK_THEATREOFBLOOD_HARD_PERFECTION_1_COMPLETED);
		t(l, "CA_TASK_THEATREOFBLOOD_HARD_PERFECTION_2_COMPLETED", VarbitID.CA_TASK_THEATREOFBLOOD_HARD_PERFECTION_2_COMPLETED);
		t(l, "CA_TASK_THEATREOFBLOOD_HARD_RESTRICTION_1_COMPLETED", VarbitID.CA_TASK_THEATREOFBLOOD_HARD_RESTRICTION_1_COMPLETED);
		t(l, "CA_TASK_THEATREOFBLOOD_HARD_RESTRICTION_2_COMPLETED", VarbitID.CA_TASK_THEATREOFBLOOD_HARD_RESTRICTION_2_COMPLETED);
		t(l, "CA_TASK_THEATREOFBLOOD_HARD_SPEED_1_COMPLETED", VarbitID.CA_TASK_THEATREOFBLOOD_HARD_SPEED_1_COMPLETED);
		t(l, "CA_TASK_THEATREOFBLOOD_HARD_SPEED_2_COMPLETED", VarbitID.CA_TASK_THEATREOFBLOOD_HARD_SPEED_2_COMPLETED);
		t(l, "CA_TASK_THEATREOFBLOOD_HARD_SPEED_3_COMPLETED", VarbitID.CA_TASK_THEATREOFBLOOD_HARD_SPEED_3_COMPLETED);
		t(l, "CA_TASK_THEATREOFBLOOD_HARD_SPEED_4_COMPLETED", VarbitID.CA_TASK_THEATREOFBLOOD_HARD_SPEED_4_COMPLETED);
		t(l, "CA_TASK_THEATREOFBLOOD_HARD_KILLCOUNT_1_COMPLETED", VarbitID.CA_TASK_THEATREOFBLOOD_HARD_KILLCOUNT_1_COMPLETED);
		t(l, "CA_TASK_THEATREOFBLOOD_STORY_MECHANICAL_1_COMPLETED", VarbitID.CA_TASK_THEATREOFBLOOD_STORY_MECHANICAL_1_COMPLETED);
		t(l, "CA_TASK_THEATREOFBLOOD_STORY_MECHANICAL_2_COMPLETED", VarbitID.CA_TASK_THEATREOFBLOOD_STORY_MECHANICAL_2_COMPLETED);
		t(l, "CA_TASK_THEATREOFBLOOD_STORY_MECHANICAL_3_COMPLETED", VarbitID.CA_TASK_THEATREOFBLOOD_STORY_MECHANICAL_3_COMPLETED);
		t(l, "CA_TASK_THEATREOFBLOOD_STORY_MECHANICAL_4_COMPLETED", VarbitID.CA_TASK_THEATREOFBLOOD_STORY_MECHANICAL_4_COMPLETED);
		t(l, "CA_TASK_THEATREOFBLOOD_STORY_MECHANICAL_5_COMPLETED", VarbitID.CA_TASK_THEATREOFBLOOD_STORY_MECHANICAL_5_COMPLETED);
		t(l, "CA_TASK_THEATREOFBLOOD_STORY_MECHANICAL_6_COMPLETED", VarbitID.CA_TASK_THEATREOFBLOOD_STORY_MECHANICAL_6_COMPLETED);
		t(l, "CA_TASK_THEATREOFBLOOD_STORY_MECHANICAL_7_COMPLETED", VarbitID.CA_TASK_THEATREOFBLOOD_STORY_MECHANICAL_7_COMPLETED);
		t(l, "CA_TASK_THEATREOFBLOOD_STORY_MECHANICAL_8_COMPLETED", VarbitID.CA_TASK_THEATREOFBLOOD_STORY_MECHANICAL_8_COMPLETED);
		t(l, "CA_TASK_THEATREOFBLOOD_STORY_MECHANICAL_9_COMPLETED", VarbitID.CA_TASK_THEATREOFBLOOD_STORY_MECHANICAL_9_COMPLETED);
		t(l, "CA_TASK_THEATREOFBLOOD_STORY_MECHANICAL_10_COMPLETED", VarbitID.CA_TASK_THEATREOFBLOOD_STORY_MECHANICAL_10_COMPLETED);
		t(l, "CA_TASK_THEATREOFBLOOD_STORY_SPEED_1_COMPLETED", VarbitID.CA_TASK_THEATREOFBLOOD_STORY_SPEED_1_COMPLETED);
		t(l, "CA_TASK_THEATREOFBLOOD_STORY_KILLCOUNT_1_COMPLETED", VarbitID.CA_TASK_THEATREOFBLOOD_STORY_KILLCOUNT_1_COMPLETED);
		t(l, "CA_TASK_GIANT_KILLCOUNT_1_COMPLETED", VarbitID.CA_TASK_GIANT_KILLCOUNT_1_COMPLETED);
		t(l, "CA_TASK_THRALL_MECHANICAL_1_COMPLETED", VarbitID.CA_TASK_THRALL_MECHANICAL_1_COMPLETED);
		t(l, "CA_TASK_LIZARDMAN_SHAMAN_PERFECTION_1_COMPLETED", VarbitID.CA_TASK_LIZARDMAN_SHAMAN_PERFECTION_1_COMPLETED);
		return Collections.unmodifiableList(l);
	}

	private static List<TierDef> buildTiers()
	{
		final List<TierDef> l = new ArrayList<>(6);
		l.add(new TierDef("EASY", VarbitID.CA_TIER_STATUS_EASY,
			VarbitID.CA_TOTAL_TASKS_COMPLETED_EASY, VarbitID.CA_THRESHOLD_EASY));
		l.add(new TierDef("MEDIUM", VarbitID.CA_TIER_STATUS_MEDIUM,
			VarbitID.CA_TOTAL_TASKS_COMPLETED_MEDIUM, VarbitID.CA_THRESHOLD_MEDIUM));
		l.add(new TierDef("HARD", VarbitID.CA_TIER_STATUS_HARD,
			VarbitID.CA_TOTAL_TASKS_COMPLETED_HARD, VarbitID.CA_THRESHOLD_HARD));
		l.add(new TierDef("ELITE", VarbitID.CA_TIER_STATUS_ELITE,
			VarbitID.CA_TOTAL_TASKS_COMPLETED_ELITE, VarbitID.CA_THRESHOLD_ELITE));
		l.add(new TierDef("MASTER", VarbitID.CA_TIER_STATUS_MASTER,
			VarbitID.CA_TOTAL_TASKS_COMPLETED_MASTER, VarbitID.CA_THRESHOLD_MASTER));
		l.add(new TierDef("GRANDMASTER", VarbitID.CA_TIER_STATUS_GRANDMASTER,
			VarbitID.CA_TOTAL_TASKS_COMPLETED_GRANDMASTER, VarbitID.CA_THRESHOLD_GRANDMASTER));
		return Collections.unmodifiableList(l);
	}

	private static Set<Integer> collectVarbitIds()
	{
		final Set<Integer> ids = new HashSet<>();
		ids.add(POINTS_VARBIT);
		for (TaskDef task : TASKS)
		{
			ids.add(task.getVarbitId());
		}
		for (TierDef tier : TIERS)
		{
			ids.add(tier.getStatusVarbitId());
			ids.add(tier.getCompletedCountVarbitId());
			ids.add(tier.getThresholdVarbitId());
		}
		return Collections.unmodifiableSet(ids);
	}
}
